// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContextFile(arg1, arg2) {
  return window['go']['main']['App']['AddContextFile'](arg1, arg2);
}

export function AddNewTab() {
  return window['go']['main']['App']['AddNewTab']();
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function CancelMessage(arg1) {
  return window['go']['main']['App']['CancelMessage'](arg1);
}

export function CancelOrchestrationJob(arg1) {
  return window['go']['main']['App']['CancelOrchestrationJob'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearConversation(arg1) {
  return window['go']['main']['App']['ClearConversation'](arg1);
}

export function CompletePath(arg1) {
  return window['go']['main']['App']['CompletePath'](arg1);
}

export function ConnectTeamsWorker(arg1, arg2) {
  return window['go']['main']['App']['ConnectTeamsWorker'](arg1, arg2);
}

export function ConnectWorkerTab(arg1, arg2) {
  return window['go']['main']['App']['ConnectWorkerTab'](arg1, arg2);
}

export function CreateClaudeMd(arg1) {
  return window['go']['main']['App']['CreateClaudeMd'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DetectInstallMethod() {
  return window['go']['main']['App']['DetectInstallMethod']();
}

export function DisconnectTeamsWorker(arg1, arg2) {
  return window['go']['main']['App']['DisconnectTeamsWorker'](arg1, arg2);
}

export function DisconnectWorkerTab(arg1, arg2) {
  return window['go']['main']['App']['DisconnectWorkerTab'](arg1, arg2);
}

export function GetAgentModel() {
  return window['go']['main']['App']['GetAgentModel']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoContextFiles(arg1) {
  return window['go']['main']['App']['GetAutoContextFiles'](arg1);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetAvailableSessions(arg1) {
  return window['go']['main']['App']['GetAvailableSessions'](arg1);
}

export function GetClaudeVersion() {
  return window['go']['main']['App']['GetClaudeVersion']();
}

export function GetContextFileContent(arg1) {
  return window['go']['main']['App']['GetContextFileContent'](arg1);
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetPlanContent(arg1) {
  return window['go']['main']['App']['GetPlanContent'](arg1);
}

export function GetReleaseNotes(arg1, arg2) {
  return window['go']['main']['App']['GetReleaseNotes'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTabSessionID(arg1) {
  return window['go']['main']['App']['GetTabSessionID'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function GetUsageInfo(arg1) {
  return window['go']['main']['App']['GetUsageInfo'](arg1);
}

export function GetWebSocketPort() {
  return window['go']['main']['App']['GetWebSocketPort']();
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function OpenChangelogPage() {
  return window['go']['main']['App']['OpenChangelogPage']();
}

export function OpenExpandedView(arg1) {
  return window['go']['main']['App']['OpenExpandedView'](arg1);
}

export function ReadFileSnippet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFileSnippet'](arg1, arg2, arg3);
}

export function RemoveContextFile(arg1, arg2) {
  return window['go']['main']['App']['RemoveContextFile'](arg1, arg2);
}

export function RemoveLastUserMessage(arg1) {
  return window['go']['main']['App']['RemoveLastUserMessage'](arg1);
}

export function RemoveTab(arg1) {
  return window['go']['main']['App']['RemoveTab'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameTab(arg1, arg2) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2);
}

export function RequestCodeReview(arg1) {
  return window['go']['main']['App']['RequestCodeReview'](arg1);
}

export function RequestContextRecommendation(arg1) {
  return window['go']['main']['App']['RequestContextRecommendation'](arg1);
}

export function SaveDroppedFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDroppedFile'](arg1, arg2);
}

export function SaveDroppedImage(arg1, arg2) {
  return window['go']['main']['App']['SaveDroppedImage'](arg1, arg2);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendAdminMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAdminMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendTeamsMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTeamsMessage'](arg1, arg2, arg3);
}

export function SetAgentModel(arg1) {
  return window['go']['main']['App']['SetAgentModel'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetWorkDir(arg1, arg2) {
  return window['go']['main']['App']['SetWorkDir'](arg1, arg2);
}

export function SwitchTabSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchTabSession'](arg1, arg2, arg3);
}

export function ToggleTabAdminMode(arg1, arg2) {
  return window['go']['main']['App']['ToggleTabAdminMode'](arg1, arg2);
}

export function ToggleTabPlanMode(arg1, arg2) {
  return window['go']['main']['App']['ToggleTabPlanMode'](arg1, arg2);
}

export function ToggleTabTeamsMode(arg1, arg2) {
  return window['go']['main']['App']['ToggleTabTeamsMode'](arg1, arg2);
}

export function TranslateReleaseNotes() {
  return window['go']['main']['App']['TranslateReleaseNotes']();
}

export function TruncateMessages(arg1, arg2) {
  return window['go']['main']['App']['TruncateMessages'](arg1, arg2);
}

export function UpdateClaude() {
  return window['go']['main']['App']['UpdateClaude']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
