// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {utils} from '../models';

export function AddContextFile(arg1:string,arg2:string):Promise<void>;

export function AddNewTab():Promise<models.TabState>;

export function CancelMessage(arg1:string):Promise<void>;

export function CancelOrchestrationJob(arg1:string):Promise<void>;

export function ClearConversation(arg1:string):Promise<void>;

export function CompletePath(arg1:string):Promise<Array<string>>;

export function ConnectWorkerTab(arg1:string,arg2:string):Promise<void>;

export function DisconnectWorkerTab(arg1:string,arg2:string):Promise<void>;

export function GetAutoContextFiles(arg1:string):Promise<Array<main.AutoContextFile>>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetClaudeVersion():Promise<string>;

export function GetContextFileContent(arg1:string):Promise<string>;

export function GetCurrentModel():Promise<string>;

export function GetFileInfo(arg1:string):Promise<utils.FileInfo>;

export function GetSettings():Promise<models.GlobalSettings>;

export function GetTabs():Promise<Array<models.TabState>>;

export function GetUsageInfo(arg1:string):Promise<models.UsageInfo>;

export function GetWebSocketPort():Promise<number>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function OpenExpandedView(arg1:string):Promise<void>;

export function ReadFileSnippet(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function RemoveContextFile(arg1:string,arg2:string):Promise<void>;

export function RemoveLastUserMessage(arg1:string):Promise<void>;

export function RemoveTab(arg1:string):Promise<void>;

export function RenameTab(arg1:string,arg2:string):Promise<void>;

export function SaveDroppedFile(arg1:string,arg2:string):Promise<string>;

export function SaveDroppedImage(arg1:string,arg2:string):Promise<string>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function SelectFiles():Promise<Array<string>>;

export function SendAdminMessage(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetWorkDir(arg1:string,arg2:string):Promise<void>;

export function ToggleTabAdminMode(arg1:string,arg2:boolean):Promise<void>;

export function ToggleTabPlanMode(arg1:string,arg2:boolean):Promise<void>;

export function TruncateMessages(arg1:string,arg2:number):Promise<void>;

export function UpdateSettings(arg1:models.GlobalSettings):Promise<void>;
