// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {claude} from '../models';
import {utils} from '../models';

export function AddContextFile(arg1:string,arg2:string):Promise<void>;

export function AddNewTab():Promise<models.TabState>;

export function AnswerQuestion(arg1:string,arg2:Record<string, string>):Promise<void>;

export function ApplyTeamPreset(arg1:string,arg2:string):Promise<void>;

export function CancelMessage(arg1:string):Promise<void>;

export function CancelOrchestrationJob(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearConversation(arg1:string):Promise<void>;

export function CompletePath(arg1:string):Promise<Array<string>>;

export function ConnectTeamsWorker(arg1:string,arg2:string):Promise<void>;

export function ConnectWorkerTab(arg1:string,arg2:string):Promise<void>;

export function CreateClaudeMd(arg1:string):Promise<string>;

export function CreateTabClaudeMd(arg1:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function DeleteTeamPreset(arg1:string):Promise<void>;

export function DetectInstallMethod():Promise<string>;

export function DisconnectTeamsWorker(arg1:string,arg2:string):Promise<void>;

export function DisconnectWorkerTab(arg1:string,arg2:string):Promise<void>;

export function GetAgentModel():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAutoContextFiles(arg1:string):Promise<Array<main.AutoContextFile>>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetAvailableSessions(arg1:string):Promise<Array<claude.SessionInfo>>;

export function GetClaudeVersion():Promise<string>;

export function GetContextFileContent(arg1:string):Promise<string>;

export function GetCurrentModel():Promise<string>;

export function GetFileInfo(arg1:string):Promise<utils.FileInfo>;

export function GetPlanContent(arg1:string):Promise<string>;

export function GetReleaseNotes(arg1:string,arg2:string):Promise<Array<main.ReleaseNote>>;

export function GetSettings():Promise<models.GlobalSettings>;

export function GetTabSessionID(arg1:string):Promise<string>;

export function GetTabs():Promise<Array<models.TabState>>;

export function GetTeamPresets():Promise<Array<models.TeamPreset>>;

export function GetUsageInfo(arg1:string):Promise<models.UsageInfo>;

export function GetWebSocketPort():Promise<number>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function OpenChangelogPage():Promise<void>;

export function OpenExpandedView(arg1:string):Promise<void>;

export function ReadFileSnippet(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function RemoveContextFile(arg1:string,arg2:string):Promise<void>;

export function RemoveLastUserMessage(arg1:string):Promise<void>;

export function RemoveTab(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameTab(arg1:string,arg2:string):Promise<void>;

export function RenameTeamPreset(arg1:string,arg2:string):Promise<void>;

export function RequestCodeReview(arg1:string):Promise<void>;

export function ResumeSessionInTerminal(arg1:string,arg2:string):Promise<void>;

export function SaveDroppedFile(arg1:string,arg2:string):Promise<string>;

export function SaveDroppedImage(arg1:string,arg2:string):Promise<string>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SaveTeamPreset(arg1:string,arg2:string):Promise<void>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function SelectFiles():Promise<Array<string>>;

export function SendAdminMessage(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SendTeamsMessage(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetAgentModel(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetWorkDir(arg1:string,arg2:string):Promise<void>;

export function SwitchTabSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ToggleTabAdminMode(arg1:string,arg2:boolean):Promise<void>;

export function ToggleTabPlanMode(arg1:string,arg2:boolean):Promise<void>;

export function ToggleTabTeamsMode(arg1:string,arg2:boolean):Promise<void>;

export function TranslateReleaseNotes():Promise<Array<main.ReleaseNote>>;

export function TruncateMessages(arg1:string,arg2:number):Promise<void>;

export function UpdateClaude():Promise<main.UpdateResult>;

export function UpdateSettings(arg1:models.GlobalSettings):Promise<void>;
